# -*- coding: utf-8 -*-
"""Final_swint_rolling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UrSyKN-EkUtUO2qCyKgayMvm6vvdxhgW

# Swin-Tiny (ViT) — Rolling Walk-Forward Training (Colab)
"""

# ─── CELL 1: MOUNT DRIVE & INSTALL DEPS ──────────────────────────────────────
from google.colab import drive
drive.mount('/content/drive')

!pip install -q torch torchvision scikit-learn matplotlib seaborn tqdm Pillow pandas numpy python-dateutil

import torch
print(f"PyTorch: {torch.__version__}")
print(f"GPU: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'NOT FOUND — check Runtime > Change runtime type > T4 GPU'}")

# ─── CELL 2: CONFIGURATION ────────────────────────────────────────────────────
import os

# ── Edit IMAGE_TYPE to switch between image types ─────────────────────────────
DRIVE_DIR  = '/content/drive/MyDrive/AI4Fin_2'
RES_DIR = '/content/drive/MyDrive/AI4Fin_3'
IMAGE_TYPE = 'heatmaps_standard5'       # 'candlesticks5' | 'heatmaps_standard5'
EXPERIMENT = 'rolling_vit_e1'
# ─────────────────────────────────────────────────────────────────────────────

MODEL_NAME  = 'swin_tiny'

# ── Drive source paths (read-only) ───────────────────────────────────────────
DRIVE_CSV       = os.path.join(DRIVE_DIR, 'dataset5', 'dataset5_rolling_windows.csv')
DRIVE_IMAGE_DIR = os.path.join(DRIVE_DIR, IMAGE_TYPE)   # plain folder — no zip needed

# ── Local working paths (fast SSD) ───────────────────────────────────────────
LOCAL_DIR  = '/content/ai4fin_local'
IMAGE_DIR  = os.path.join(LOCAL_DIR, IMAGE_TYPE)
META_CSV   = os.path.join(LOCAL_DIR, 'dataset5_rolling_windows.csv')

# ── Results go to Drive (persist across sessions) ────────────────────────────
RESULTS_DIR = os.path.join(RES_DIR, 'results', f'{IMAGE_TYPE}_{EXPERIMENT}')

BATCH_SIZE    = 96
MAX_EPOCHS    = 75
WARMUP_EPOCHS = 5
FREEZE_EPOCHS = 5
WEIGHT_DECAY  = 1e-4
PATIENCE_ES   = 15
SEED          = 42

CLASS_NAMES  = ['Bearish', 'Bullish', 'Neutral']
LABEL_TO_IDX = {'Bearish': 0, 'Bullish': 1, 'Neutral': 2}
NUM_CLASSES  = 3

os.makedirs(LOCAL_DIR,   exist_ok=True)
os.makedirs(RESULTS_DIR, exist_ok=True)
os.makedirs(os.path.join(DRIVE_DIR, 'results'), exist_ok=True)

print(f'Model           : {MODEL_NAME}')
print(f'Image type      : {IMAGE_TYPE}')
print(f'Experiment      : {EXPERIMENT}')
print(f'Drive CSV       : {DRIVE_CSV}  (exists: {os.path.exists(DRIVE_CSV)})')
print(f'Drive image dir : {DRIVE_IMAGE_DIR}  (exists: {os.path.exists(DRIVE_IMAGE_DIR)})')
print(f'Local imgs      : {IMAGE_DIR}')
print(f'Local CSV       : {META_CSV}')
print(f'Results         : {RESULTS_DIR}')
print(f'Batch size      : {BATCH_SIZE}')

# ─── CELL 3: COPY DATA TO LOCAL SSD ──────────────────────────────────────────
# Reads ZIP and CSV from Drive once per session, stores on fast local SSD.
# Safe to re-run: skips extraction if already present.
# ─────────────────────────────────────────────────────────────────────────────
import shutil
import zipfile
import os
from tqdm.auto import tqdm

LOCAL_DIR       = '/content/ai4fin_local'
LOCAL_IMAGE_DIR = os.path.join(LOCAL_DIR, IMAGE_TYPE)
LOCAL_META_CSV  = os.path.join(LOCAL_DIR, 'dataset5_rolling_windows.csv')

# Pointing to a zip file in the BASE_DIR (e.g. 'candlesticks5.zip')
DRIVE_ZIP_PATH  = os.path.join(DRIVE_DIR, f'{IMAGE_TYPE}.zip')

os.makedirs(LOCAL_DIR, exist_ok=True)

# ── CSV ────────────────────────────────────────────────────────────────────────
if not os.path.exists(LOCAL_META_CSV):
    print('Copying CSV from Drive...')
    shutil.copy2(DRIVE_CSV, LOCAL_META_CSV)
    print(f'  Done → {LOCAL_META_CSV}')
else:
    print('CSV already present locally.')

# ── Images (from ZIP) ───────────────────────────────────────────────────────
already_copied = (
    os.path.exists(LOCAL_IMAGE_DIR) and
    all(os.path.exists(os.path.join(LOCAL_IMAGE_DIR, lbl)) for lbl in CLASS_NAMES) and
    sum(len(os.listdir(os.path.join(LOCAL_IMAGE_DIR, lbl)))
        for lbl in CLASS_NAMES
        if os.path.exists(os.path.join(LOCAL_IMAGE_DIR, lbl))) > 100
)

if already_copied:
    print(f'Images already present at {LOCAL_IMAGE_DIR}')
else:
    if not os.path.exists(DRIVE_ZIP_PATH):
        raise FileNotFoundError(
            f'Drive zip not found: {DRIVE_ZIP_PATH}\n'
            f'Ensure {IMAGE_TYPE}.zip exists in your Google Drive folder {DRIVE_DIR}.'
        )

    print(f'Extracting {IMAGE_TYPE}.zip from Drive to local SSD...')
    with zipfile.ZipFile(DRIVE_ZIP_PATH, 'r') as zip_ref:
        # Detect zip internal structure
        sample_names = zip_ref.namelist()[:20]
        has_parent_dir = any(name.startswith(f"{IMAGE_TYPE}/") for name in sample_names)

        # If zip includes the parent folder, extract to LOCAL_DIR.
        # If it just contains 'Bearish', 'Bullish', etc., extract straight to LOCAL_IMAGE_DIR.
        extract_path = LOCAL_DIR if has_parent_dir else LOCAL_IMAGE_DIR
        os.makedirs(extract_path, exist_ok=True)

        zip_ref.extractall(extract_path)
    print('Extraction complete.')

# ── Redirect IMAGE_DIR and META_CSV to local paths ───────────────────────────
IMAGE_DIR = LOCAL_IMAGE_DIR
META_CSV  = LOCAL_META_CSV

# ── Verify ────────────────────────────────────────────────────────────────────
print('\nImage counts (local):')
total = 0
for lbl in CLASS_NAMES:
    p = os.path.join(IMAGE_DIR, lbl)
    n = len(os.listdir(p)) if os.path.exists(p) else 0
    total += n
    print(f'  {lbl}: {n:,}')
print(f'  Total: {total:,}')
print(f'  CSV  : {META_CSV}')

if total < 100:
    print('\nWARNING: Very few images extracted. Check that the zip file structure matches the expected folder structure.')

# ─── CELL 4: IMPORTS, SEED, DEVICE ───────────────────────────────────────────
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm.auto import tqdm

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms
from torchvision.models import swin_t, Swin_T_Weights
from PIL import Image

from sklearn.metrics import (
    accuracy_score, precision_recall_fscore_support, recall_score,
    cohen_kappa_score, matthews_corrcoef, confusion_matrix,
    classification_report, roc_auc_score,
)

def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = False
    torch.backends.cudnn.benchmark = True

seed_everything(SEED)
DEVICE  = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
USE_AMP = DEVICE.type == 'cuda'
print(f'Device: {DEVICE}   AMP: {USE_AMP}')

# ─── CELL 5: DATASET, TRANSFORMS, MODEL ──────────────────────────────────────
# ─── CELL 5: DATASET, TRANSFORMS, MODEL ──────────────────────────────────────

class RollingWindowDataset(Dataset):
    def __init__(self, df, image_dir, transform=None):
        self.transform = transform
        self.samples = []
        missing = 0
        for _, row in df.iterrows():
            fname = f"{row['ticker']}_{int(row['window_row_start'])}_{int(row['window_row_end'])}.png"
            path  = os.path.join(image_dir, row['label'], fname)
            if os.path.exists(path):
                self.samples.append((path, LABEL_TO_IDX[row['label']], float(row['pct_change'])))
            else:
                missing += 1
        if missing:
            print(f'      {missing} image files not found and skipped.')

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        path, label, _ = self.samples[idx]
        img = Image.open(path).convert('RGB')
        if self.transform:
            img = self.transform(img)
        return img, label

    @property
    def pct_changes(self):
        return [s[2] for s in self.samples]

    @property
    def targets(self):
        return [s[1] for s in self.samples]


_MEAN = [0.485, 0.456, 0.406]
_STD  = [0.229, 0.224, 0.225]

base_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=_MEAN, std=_STD),
])

# ── Fix 5: ColorJitter removed ────────────────────────────────────────────────
# ColorJitter corrupts GASF mathematical encoding and the green/red candle ─────
# color semantics. RandomErasing kept at very small scale (0.01-0.04) only ─────
# as a structural dropout regulariser, not an image-content augmentation. ──────
train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=_MEAN, std=_STD),
    transforms.RandomErasing(p=0.1, scale=(0.01, 0.04)),
])

class AI4FinSwinT(nn.Module):
    """Swin-Tiny wrapper for 3-class financial chart classification.

    Architecture notes
    ------------------
    torchvision's Swin-T `features` has 8 sub-modules:
        [0] Patch embedding  (Conv2d 4×4 stride 4 + LayerNorm)
        [1] Stage 1          (2 × SwinTransformerBlock, 96-d)
        [2] Patch merging 1  (downsample 2×, 96 → 192)
        [3] Stage 2          (2 × SwinTransformerBlock, 192-d)
        [4] Patch merging 2  (downsample 2×, 192 → 384)
        [5] Stage 3          (6 × SwinTransformerBlock, 384-d)
        [6] Patch merging 3  (downsample 2×, 384 → 768)
        [7] Stage 4          (2 × SwinTransformerBlock, 768-d)

    Classifier head:  norm → adaptive_avg_pool → flatten → head(Linear)
    We replace `head` with Dropout(0.5) → Linear(768, 3).
    """

    def __init__(self):
        super().__init__()
        base = swin_t(weights=Swin_T_Weights.IMAGENET1K_V1)

        # ── Replace classifier head ──────────────────────────────────────
        in_features = base.head.in_features          # 768
        base.head = nn.Sequential(
            nn.Dropout(p=0.5),
            nn.Linear(in_features, NUM_CLASSES),
        )
        for m in base.head.modules():
            if isinstance(m, nn.Linear):
                nn.init.trunc_normal_(m.weight, std=0.02)
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)

        self.backbone = base

    def forward(self, x):
        return self.backbone(x)


# ── Verify architecture & parameter groups ────────────────────────────────────
_tmp = AI4FinSwinT()
total_params = sum(p.numel() for p in _tmp.parameters())
train_params = sum(p.numel() for p in _tmp.parameters() if p.requires_grad)
print(f'Swin-Tiny total params : {total_params:,}')
print(f'Swin-Tiny trainable    : {train_params:,}')
print(f'Features sub-modules   : {len(_tmp.backbone.features)}')
for i, m in enumerate(_tmp.backbone.features):
    n = sum(p.numel() for p in m.parameters())
    print(f'  features[{i}] — {m.__class__.__name__:30s} params={n:>10,}')
del _tmp

print('\nDataset, transforms, and model class defined.')

# ─── CELL 6: TRAIN / EVAL FUNCTIONS ──────────────────────────────────────────

def train_epoch(model, loader, optimizer, criterion, scaler):
    model.train()
    running_loss = 0.0
    all_preds, all_labels = [], []
    for inputs, labels in tqdm(loader, desc='    train', leave=False):
        inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
        optimizer.zero_grad()
        if USE_AMP:
            with torch.amp.autocast('cuda'):
                outputs = model(inputs)
                loss    = criterion(outputs, labels)
            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            scaler.step(optimizer)
            scaler.update()
        else:
            outputs = model(inputs)
            loss    = criterion(outputs, labels)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
        running_loss += loss.item() * inputs.size(0)
        all_preds.append(torch.argmax(outputs.detach(), dim=1).cpu())
        all_labels.append(labels.cpu())
    all_preds  = torch.cat(all_preds).numpy()
    all_labels = torch.cat(all_labels).numpy()
    _, _, macro_f1, _ = precision_recall_fscore_support(
        all_labels, all_preds, average='macro', zero_division=0)
    return running_loss / len(loader.dataset), accuracy_score(all_labels, all_preds), macro_f1


def eval_epoch(model, loader, criterion):
    model.eval()
    running_loss = 0.0
    all_preds, all_labels, all_probs = [], [], []
    with torch.no_grad():
        for inputs, labels in tqdm(loader, desc='    eval ', leave=False):
            inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
            if USE_AMP:
                with torch.amp.autocast('cuda'):
                    outputs = model(inputs)
                    loss    = criterion(outputs, labels)
            else:
                outputs = model(inputs)
                loss    = criterion(outputs, labels)
            running_loss += loss.item() * inputs.size(0)
            probs = torch.softmax(outputs.float(), dim=1)  # float32 to avoid fp16 overflow → NaN
            all_preds.append(torch.argmax(probs, dim=1).cpu())
            all_labels.append(labels.cpu())
            all_probs.append(probs.cpu())
    all_preds  = torch.cat(all_preds).numpy()
    all_labels = torch.cat(all_labels).numpy()
    all_probs  = torch.cat(all_probs).numpy()
    _, _, macro_f1, _ = precision_recall_fscore_support(
        all_labels, all_preds, average='macro', zero_division=0)
    recall_pc = recall_score(all_labels, all_preds, labels=[0,1,2], average=None, zero_division=0)
    try:
        auc = roc_auc_score(all_labels, all_probs, multi_class='ovr', average='macro')
    except ValueError:
        auc = None
    return (running_loss / len(loader.dataset),
            accuracy_score(all_labels, all_preds),
            macro_f1, auc, all_preds, all_labels, all_probs, recall_pc)

print('Train/eval functions defined.')

# ─── CELL 7: PLOT HELPERS ────────────────────────────────────────────────────

def plot_training_curves(history_df, walk_id, best_epoch, save_dir):
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
    for ax, tc, vc, title in [
        (ax1, 'train_loss', 'val_loss', 'Loss'),
        (ax2, 'train_f1',  'val_f1',   'Macro-F1'),
    ]:
        ax.plot(history_df['epoch'], history_df[tc], label='Train')
        ax.plot(history_df['epoch'], history_df[vc], label='Val')
        ax.axvline(best_epoch, color='k', linestyle='--', alpha=0.5, label='Best')
        ax.set_title(f'Walk {walk_id:02d} — {title} (Swin-T)')
        ax.set_xlabel('Epoch')
        ax.legend()
    fig.tight_layout()
    fig.savefig(os.path.join(save_dir, f'walk_{walk_id:02d}_training_curves.png'), dpi=100)
    plt.show()


def plot_confusion_matrix(labels, preds, walk_id, save_dir):
    cm      = confusion_matrix(labels, preds)
    cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)
    annot   = np.array([[f'{v:.1%}\n({c})' for v, c in zip(rn, rc)]
                         for rn, rc in zip(cm_norm, cm)])
    fig, ax = plt.subplots(figsize=(7, 6))
    sns.heatmap(cm_norm, annot=annot, fmt='', cmap='Blues',
                xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES, ax=ax)
    ax.set_ylabel('True')
    ax.set_xlabel('Predicted')
    ax.set_title(f'Walk {walk_id:02d} — Confusion Matrix (Swin-T)')
    fig.tight_layout()
    fig.savefig(os.path.join(save_dir, f'walk_{walk_id:02d}_confusion_matrix.png'), dpi=100)
    plt.show()


def plot_aggregated(results_df, save_dir):
    walk_labels = [f"W{w}" for w in results_df['walk_id']]
    x = np.arange(len(walk_labels))
    for metric, ylabel, fname in [
        ('test_macro_f1', 'Test Macro-F1', 'agg_test_f1.png'),
        ('test_auc',      'Test AUC-ROC',  'agg_test_auc.png'),
        ('sharpe_ratio',  'Sharpe Ratio',  'agg_sharpe.png'),
    ]:
        vals     = pd.to_numeric(results_df[metric], errors='coerce')
        mean_val = vals.dropna().mean()
        fig, ax  = plt.subplots(figsize=(max(10, len(walk_labels)), 5))
        ax.bar(x, vals.fillna(0), 0.6, color='steelblue')
        ax.axhline(mean_val, color='red', linestyle='--', label=f'Mean={mean_val:.4f}')
        ax.set_xticks(x)
        ax.set_xticklabels(walk_labels)
        ax.set_ylabel(ylabel)
        ax.set_title(f'{ylabel} per Walk — {IMAGE_TYPE}/{EXPERIMENT} (Swin-T)')
        ax.legend()
        fig.tight_layout()
        fig.savefig(os.path.join(save_dir, fname), dpi=100)
        plt.show()

print('Plot helpers defined.')

# ─── CELL 8: MAIN WALK LOOP ──────────────────────────────────────────────────

def financial_metrics(test_preds, pct_changes, fwd_dates=None):
    """
    Portfolio-level financial metrics.
    - Sharpe: daily portfolio returns (mean across stocks per day), active days only.
    - MDD: relative drawdown on compounded daily portfolio equity curve.
    - Profit factor, win rate, total trades: individual active trades.
    """
    FWD_DAYS = 5
    positions     = np.zeros(len(test_preds))
    positions[test_preds == LABEL_TO_IDX['Bullish']] =  1.0
    positions[test_preds == LABEL_TO_IDX['Bearish']] = -1.0
    trade_returns = positions * pct_changes

    # ── Portfolio daily returns ───────────────────────────────────────────────
    if fwd_dates is not None:
        dates    = pd.to_datetime(fwd_dates)
        daily_df = pd.DataFrame({'ret': trade_returns, 'date': dates})
        daily    = daily_df.groupby('date')['ret'].mean().sort_index().values
    else:
        daily = trade_returns

    # ── Sharpe on active days only ────────────────────────────────────────────
    active_daily = daily[daily != 0]
    if len(active_daily) >= 2 and active_daily.std() > 0:
        sharpe = float((active_daily.mean() / active_daily.std()) * np.sqrt(252 / FWD_DAYS))
    else:
        sharpe = 0.0

    # ── MDD on compound equity curve ──────────────────────────────────────────
    equity       = np.cumprod(1 + daily)
    peak         = np.maximum.accumulate(equity)
    max_drawdown = float(((equity - peak) / peak).min())

    # ── Trade-level metrics ───────────────────────────────────────────────────
    active        = trade_returns[trade_returns != 0]
    pos_ret       = trade_returns[trade_returns > 0].sum()
    neg_ret       = trade_returns[trade_returns < 0].sum()
    profit_factor = float(pos_ret / abs(neg_ret)) if neg_ret != 0 else float('inf')
    total_trades  = int(len(active))
    win_rate      = float((active > 0).sum() / total_trades) if total_trades > 0 else 0.0

    return sharpe, max_drawdown, profit_factor, win_rate, total_trades


meta_df  = pd.read_csv(META_CSV)
walk_ids = sorted(meta_df['walk_id'].unique())
num_workers = 4   # Colab typically has 2 CPU cores
print(f'Metadata: {len(meta_df):,} rows | {len(walk_ids)} walks')

all_walk_results = []

for walk_id in walk_ids:
    print(f"\n{'='*60}")
    print(f"  WALK {walk_id} / {len(walk_ids)}  [Swin-Tiny]")
    print(f"{'='*60}")

    model_path  = os.path.join(RESULTS_DIR, f'walk_{walk_id:02d}_best_model.pth')
    log_path    = os.path.join(RESULTS_DIR, f'walk_{walk_id:02d}_training_log.csv')
    result_path = os.path.join(RESULTS_DIR, f'walk_{walk_id:02d}_result.csv')

    # ── Graceful resume — skip completed walks ────────────────────────────
    if os.path.exists(model_path) and os.path.exists(result_path):
        print(f'  Walk {walk_id} already done — loading saved result.')
        all_walk_results.append(pd.read_csv(result_path).iloc[0].to_dict())
        continue

    walk_df  = meta_df[meta_df['walk_id'] == walk_id]
    train_df = walk_df[walk_df['split'] == 'train']
    val_df   = walk_df[walk_df['split'] == 'val']
    test_df  = walk_df[walk_df['split'] == 'test']

    train_ds = RollingWindowDataset(train_df, IMAGE_DIR, transform=train_transform)
    val_ds   = RollingWindowDataset(val_df,   IMAGE_DIR, transform=base_transform)
    test_ds  = RollingWindowDataset(test_df,  IMAGE_DIR, transform=base_transform)

    print(f'  Loaded — Train: {len(train_ds):,}/{len(train_df):,} | '
          f'Val: {len(val_ds):,}/{len(val_df):,} | '
          f'Test: {len(test_ds):,}/{len(test_df):,}')

    pw = dict(num_workers=num_workers, pin_memory=True, persistent_workers=(num_workers > 0))
    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  **pw)
    val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False, **pw)
    test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False, **pw)

    model = AI4FinSwinT().to(DEVICE)

    # ── Progressive unfreezing: freeze early stages for first N epochs ─────
    # This prevents destructive gradient updates to low-level pretrained
    # features while the randomly-initialized head stabilises.
    # (Swin-T V2 paper recommends layer-wise LR decay of 0.95 + warmup;
    #  medical-imaging Swin-T papers use 5-epoch warmup + freeze.)
    for i in range(4):   # features[0:4] = patch embed + stage1 + merge + stage2
        for p in model.backbone.features[i].parameters():
            p.requires_grad = False
    for i in range(4, 8):  # features[4:8] stays trainable from the start
        for p in model.backbone.features[i].parameters():
            p.requires_grad = True
    for p in model.backbone.norm.parameters():
        p.requires_grad = True
    for p in model.backbone.head.parameters():
        p.requires_grad = True

    class_counts  = np.bincount(train_ds.targets, minlength=NUM_CLASSES)
    class_weights = len(train_ds.targets) / (NUM_CLASSES * class_counts + 1e-6)
    criterion = nn.CrossEntropyLoss(weight=torch.FloatTensor(class_weights).to(DEVICE))

    # ── Differential LR (conservative for ViT fine-tuning) ────────────────
    # Backed by Swin-T V2: layer-wise decay 0.95 from head → early layers.
    # Early stages start frozen, so their LR only matters after unfreezing.
    # features[0:4] = patch embed + stage 1 + patch merge 1 + stage 2
    # features[4:8] = patch merge 2 + stage 3 + patch merge 3 + stage 4
    # norm + head   = classifier head
    early_params = []
    for i in range(4):
        early_params.extend(model.backbone.features[i].parameters())
    later_params = []
    for i in range(4, 8):
        later_params.extend(model.backbone.features[i].parameters())
    head_params = list(model.backbone.norm.parameters()) + \
                  list(model.backbone.head.parameters())

    TARGET_LRS = [1e-6, 1e-5, 3e-4]  # early, later, head (peak after warmup)

    optimizer = optim.AdamW([
        {'params': early_params, 'lr': TARGET_LRS[0]},
        {'params': later_params, 'lr': TARGET_LRS[1]},
        {'params': head_params,  'lr': TARGET_LRS[2]},
    ], weight_decay=WEIGHT_DECAY)

    # ── Warmup + ReduceLROnPlateau ────────────────────────────────────────
    # Linear warmup for WARMUP_EPOCHS, then hand off to plateau scheduler.
    # During warmup, LR ramps from ~0 to TARGET_LR per group.
    def warmup_lambda(epoch):
        if epoch < WARMUP_EPOCHS:
            return (epoch + 1) / WARMUP_EPOCHS   # 0.2, 0.4, 0.6, 0.8, 1.0
        return 1.0   # after warmup, LR stays at target (plateau scheduler takes over)

    warmup_scheduler = optim.lr_scheduler.LambdaLR(optimizer, lr_lambda=warmup_lambda)
    plateau_scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode='max', factor=0.3, patience=7, min_lr=1e-7)
    scaler = torch.amp.GradScaler('cuda') if USE_AMP else None

    best_val_f1 = 0.0
    best_epoch  = 1
    patience_counter = 0
    best_state  = None
    history     = []

    for epoch in range(1, MAX_EPOCHS + 1):

        # ── Progressive unfreezing: unfreeze early stages after FREEZE_EPOCHS
        if epoch == FREEZE_EPOCHS + 1:
            print(f'    ↳ Unfreezing early backbone stages (features[0:4])...')
            for i in range(4):
                for p in model.backbone.features[i].parameters():
                    p.requires_grad = True

        tr_loss, tr_acc, tr_f1 = train_epoch(model, train_loader, optimizer, criterion, scaler)
        vl_loss, vl_acc, vl_f1, vl_auc, _, _, _, recall_pc = eval_epoch(model, val_loader, criterion)

        # ── Scheduler logic: warmup first, then plateau ───────────────────
        if epoch <= WARMUP_EPOCHS:
            warmup_scheduler.step()
        else:
            plateau_scheduler.step(vl_f1)

        lr = optimizer.param_groups[-1]['lr']   # report head LR (most readable)

        print(f"  Ep {epoch:02d}/{MAX_EPOCHS} | "
              f"TrLoss={tr_loss:.4f} TrF1={tr_f1:.4f} | "
              f"VLoss={vl_loss:.4f} VF1={vl_f1:.4f} "
              f"VAUC={f'{vl_auc:.4f}' if vl_auc is not None else 'N/A'} | "
              f"Rec: Be={recall_pc[0]:.2f} Bu={recall_pc[1]:.2f} Ne={recall_pc[2]:.2f} | "
              f"LR={lr:.2e}")

        history.append({
            'walk_id': walk_id, 'epoch': epoch,
            'train_loss': tr_loss, 'train_acc': tr_acc, 'train_f1': tr_f1,
            'val_loss':   vl_loss, 'val_acc':   vl_acc, 'val_f1':   vl_f1,
            'val_auc':    vl_auc,  'lr':        lr,
        })

        if vl_f1 > best_val_f1:
            best_val_f1 = vl_f1
            best_epoch  = epoch
            best_state  = {k: v.cpu().clone() for k, v in model.state_dict().items()}
            patience_counter = 0
            print(f'    ★ New best  F1={vl_f1:.4f}')
        else:
            patience_counter += 1

        if patience_counter >= PATIENCE_ES:
            print(f'  Early stopping at epoch {epoch}.')
            break

    history_df = pd.DataFrame(history)
    history_df.to_csv(log_path, index=False)
    plot_training_curves(history_df, walk_id, best_epoch, RESULTS_DIR)

    model.load_state_dict({k: v.to(DEVICE) for k, v in best_state.items()})
    torch.save(best_state, model_path)

    te_loss, te_acc, te_f1, te_auc, te_preds, te_labels, te_probs, _ = \
        eval_epoch(model, test_loader, criterion)

    plot_confusion_matrix(te_labels, te_preds, walk_id, RESULTS_DIR)

    kappa = cohen_kappa_score(te_labels, te_preds)
    mcc   = matthews_corrcoef(te_labels, te_preds)
    print(f'\n  Classification Report — Walk {walk_id} (Swin-T):')
    print(classification_report(te_labels, te_preds, target_names=CLASS_NAMES, zero_division=0))

    sharpe, max_dd, pf, wr, n_trades = financial_metrics(
        te_preds, np.array(test_ds.pct_changes))

    walk_result = {
        'walk_id': walk_id, 'best_val_f1': best_val_f1,
        'test_accuracy': te_acc, 'test_macro_f1': te_f1, 'test_auc': te_auc,
        'cohen_kappa': kappa, 'mcc': mcc,
        'sharpe_ratio': sharpe, 'max_drawdown': max_dd,
        'profit_factor': pf, 'win_rate': wr, 'total_trades': n_trades,
    }
    all_walk_results.append(walk_result)
    pd.DataFrame([walk_result]).to_csv(result_path, index=False)

    auc_str = f'{te_auc:.4f}' if te_auc is not None else 'N/A'
    print(f'\n  Walk {walk_id} Test: Acc={te_acc:.4f} F1={te_f1:.4f} '
          f'AUC={auc_str} Kappa={kappa:.4f} MCC={mcc:.4f} Sharpe={sharpe:.4f}')

    del model, optimizer, warmup_scheduler, plateau_scheduler, criterion
    del train_loader, val_loader, test_loader
    del train_ds, val_ds, test_ds
    if scaler is not None: del scaler
    torch.cuda.empty_cache()

# ─── CELL 9: AGGREGATE RESULTS ───────────────────────────────────────────────

results_df = pd.DataFrame(all_walk_results)
results_df.to_csv(os.path.join(RESULTS_DIR, 'per_walk_results.csv'), index=False)

pf_clean = results_df['profit_factor'].replace([np.inf, -np.inf], np.nan)
avg = {
    'Image Type':        IMAGE_TYPE,
    'Experiment':        EXPERIMENT,
    'Num Walks':         len(walk_ids),
    'Avg Best Val F1':   results_df['best_val_f1'].mean(),
    'Avg Test Accuracy': results_df['test_accuracy'].mean(),
    'Avg Test Macro-F1': results_df['test_macro_f1'].mean(),
    'Std Test Macro-F1': results_df['test_macro_f1'].std(),
    'Avg Test AUC':      results_df['test_auc'].dropna().mean(),
    'Std Test AUC':      results_df['test_auc'].dropna().std(),
    'Avg Cohen Kappa':   results_df['cohen_kappa'].mean(),
    'Avg MCC':           results_df['mcc'].mean(),
    'Avg Sharpe Ratio':  results_df['sharpe_ratio'].mean(),
    'Std Sharpe Ratio':  results_df['sharpe_ratio'].std(),
    'Avg Max Drawdown':  results_df['max_drawdown'].mean(),
    'Avg Profit Factor': pf_clean.mean(),
    'Avg Win Rate':      results_df['win_rate'].mean(),
    'Avg Total Trades':  results_df['total_trades'].mean(),
}

summary_df = pd.DataFrame([avg])
print('\n' + '='*60)
print('FINAL AGGREGATED RESULTS')
print('='*60)
display(summary_df.T.rename(columns={0: 'Value'}))

summary_df.to_csv(os.path.join(RESULTS_DIR, 'aggregated_summary.csv'), index=False)

master_path = os.path.join(DRIVE_DIR, 'results', 'all_experiments_summary.csv')
if os.path.exists(master_path):
    master_df = pd.concat([pd.read_csv(master_path), summary_df], ignore_index=True)
else:
    master_df = summary_df
master_df.to_csv(master_path, index=False)
print(f'\nAppended to master: {master_path}')

plot_aggregated(results_df, RESULTS_DIR)
print(f'\nAll results saved to: {RESULTS_DIR}')