# -*- coding: utf-8 -*-
"""Final_lstm_baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OccuBNGOUzO4jwBG9crVQq54bKFm6Yhm

## LSTM Baseline — Rolling Walk-Forward Training + Inference
"""

# ═══════════════════════════════════════════════════════════════════════════════
# CELL 1 — MOUNT DRIVE & INSTALL
# ═══════════════════════════════════════════════════════════════════════════════
from google.colab import drive
drive.mount('/content/drive')

!pip install -q torch scikit-learn matplotlib seaborn tqdm pandas numpy openpyxl

import torch
print(f"PyTorch: {torch.__version__}")
print(f"GPU: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU only'}")

# ═══════════════════════════════════════════════════════════════════════════════
# CELL 2 — CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════
import os

DRIVE_DIR   = '/content/drive/MyDrive/AI4Fin_2'
META_CSV    = os.path.join(DRIVE_DIR,'dataset5', 'dataset5_rolling_windows.csv')
PRICE_DIR   = os.path.join(DRIVE_DIR, 'egx_stock_data')    # folder with {TICKER}_price.csv files
RESULTS_DIR = os.path.join(DRIVE_DIR, 'results', 'lstm_baseline')

# ── Variants to run ───────────────────────────────────────────────────────────
# Comment out any you don't want to run this session.
VARIANTS = [
    {
        'name':       'LSTM_Raw',
        'use_ti':     False,       # OHLCV only (40 × 5)
        'input_size': 5,
    },
    {
        'name':       'LSTM_TI',
        'use_ti':     True,        # OHLCV + 5 technical indicators (40 × 10)
        'input_size': 10,
    },
]

# ── Model hyperparameters ───────────────
HIDDEN_SIZE  = 64
NUM_LAYERS   = 2          # fewer layers to avoid overfitting on ~150K samples
DROPOUT      = 0.3        # regularization
WINDOW_SIZE  = 40         # must match image lookback for fair comparison

# ── Training (matches Swin-T notebook exactly) ────────────────────────────────
BATCH_SIZE   = 256        # LSTM is tiny — can use larger batches
MAX_EPOCHS   = 75
WEIGHT_DECAY = 1e-4
LR           = 1e-3       # standard for LSTM training from scratch
PATIENCE_ES  = 15
SEED         = 42

CLASS_NAMES  = ['Bearish', 'Bullish', 'Neutral']
LABEL_TO_IDX = {'Bearish': 0, 'Bullish': 1, 'Neutral': 2}
IDX_TO_LABEL = {0: 'Bearish', 1: 'Bullish', 2: 'Neutral'}
NUM_CLASSES  = 3
FWD_DAYS     = 5

os.makedirs(RESULTS_DIR, exist_ok=True)

print(f'Meta CSV  : {META_CSV}  (exists: {os.path.exists(META_CSV)})')
print(f'Price dir : {PRICE_DIR}  (exists: {os.path.exists(PRICE_DIR)})')
print(f'Results   : {RESULTS_DIR}')
print(f'Variants  : {[v["name"] for v in VARIANTS]}')
print(f'Model     : LSTM(hidden={HIDDEN_SIZE}, layers={NUM_LAYERS}, dropout={DROPOUT})')
print(f'Window    : {WINDOW_SIZE} days')

# ═══════════════════════════════════════════════════════════════════════════════
# CELL 3 — IMPORTS, SEED, DEVICE
# ═══════════════════════════════════════════════════════════════════════════════
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm.auto import tqdm
from collections import OrderedDict

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset

from sklearn.metrics import (
    accuracy_score, precision_recall_fscore_support, recall_score,
    cohen_kappa_score, matthews_corrcoef, confusion_matrix,
    classification_report, roc_auc_score,
)

def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = False
    torch.backends.cudnn.benchmark = True

seed_everything(SEED)
DEVICE  = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
USE_AMP = DEVICE.type == 'cuda'
print(f'Device: {DEVICE}   AMP: {USE_AMP}')

# ═══════════════════════════════════════════════════════════════════════════════
# CELL 4 — LOAD & PREPROCESS PRICE DATA
# ═══════════════════════════════════════════════════════════════════════════════
# Load all per-ticker OHLCV files into a dict.
# Pre-compute technical indicators on full history so we can slice any window.
# ═══════════════════════════════════════════════════════════════════════════════

meta_df = pd.read_csv(META_CSV)
tickers = sorted(meta_df['ticker'].unique())
print(f'Metadata: {len(meta_df):,} rows | {meta_df["walk_id"].nunique()} walks | {len(tickers)} tickers')

# ── Load all price files ──────────────────────────────────────────────────────
price_data = {}
for ticker in tickers:
    fpath = os.path.join(PRICE_DIR, f'{ticker}_price.csv')
    if not os.path.exists(fpath):
        print(f'  WARNING: {fpath} not found!')
        continue
    df = pd.read_csv(fpath)
    price_data[ticker] = df

print(f'Loaded {len(price_data)} price files')

# ── Compute technical indicators on full history ──────────────────────────────
def compute_technical_indicators(df):
    """Add 5 technical indicators to an OHLCV DataFrame (computed on full history)."""
    close = df['Close'].values.astype(float)
    high  = df['High'].values.astype(float)
    low   = df['Low'].values.astype(float)
    volume = df['Volume'].values.astype(float)
    n = len(df)

    # 1. RSI (14-period)
    delta = np.diff(close, prepend=close[0])
    gain = np.where(delta > 0, delta, 0.0)
    loss = np.where(delta < 0, -delta, 0.0)
    avg_gain = np.full(n, np.nan)
    avg_loss = np.full(n, np.nan)
    if n >= 15:
        avg_gain[14] = gain[1:15].mean()
        avg_loss[14] = loss[1:15].mean()
        for i in range(15, n):
            avg_gain[i] = (avg_gain[i-1] * 13 + gain[i]) / 14
            avg_loss[i] = (avg_loss[i-1] * 13 + loss[i]) / 14
    rs = avg_gain / (avg_loss + 1e-10)
    rsi = 100 - (100 / (1 + rs))
    df['RSI'] = rsi

    # 2. MACD (12, 26, 9)
    ema12 = pd.Series(close).ewm(span=12, adjust=False).mean().values
    ema26 = pd.Series(close).ewm(span=26, adjust=False).mean().values
    macd_line = ema12 - ema26
    signal_line = pd.Series(macd_line).ewm(span=9, adjust=False).mean().values
    df['MACD'] = macd_line
    df['MACD_Signal'] = signal_line

    # 3. Bollinger Band width (20-period, 2 std)
    sma20 = pd.Series(close).rolling(20).mean().values
    std20 = pd.Series(close).rolling(20).std().values
    bb_upper = sma20 + 2 * std20
    bb_lower = sma20 - 2 * std20
    bb_width = (bb_upper - bb_lower) / (sma20 + 1e-10)
    df['BB_Width'] = bb_width

    # 4. Volume SMA ratio (volume / SMA(volume, 20))
    vol_sma20 = pd.Series(volume).rolling(20).mean().values
    df['Vol_Ratio'] = volume / (vol_sma20 + 1e-10)

    return df


for ticker in tickers:
    if ticker in price_data:
        price_data[ticker] = compute_technical_indicators(price_data[ticker])

# Show sample
sample_ticker = tickers[0]
print(f'\nSample ({sample_ticker}) columns: {price_data[sample_ticker].columns.tolist()}')
print(price_data[sample_ticker][['Close', 'RSI', 'MACD', 'BB_Width', 'Vol_Ratio']].tail(3))
print('\nPrice data with TIs ready.')

# ═══════════════════════════════════════════════════════════════════════════════
# CELL 5 — DATASET CLASS
# ═══════════════════════════════════════════════════════════════════════════════
# Returns normalized OHLCV (+ optional TI) sequences for each sample.
# Min-max normalization per window:
#   - O/H/L/C normalized together (same price scale)
#   - Volume normalized separately
#   - Each TI normalized separately
# ═══════════════════════════════════════════════════════════════════════════════

OHLCV_COLS = ['Open', 'High', 'Low', 'Close', 'Volume']
TI_COLS    = ['RSI', 'MACD', 'MACD_Signal', 'BB_Width', 'Vol_Ratio']

class OHLCVDataset(Dataset):
    """Dataset that returns normalized OHLCV (± TI) sequences from price files."""

    def __init__(self, df, price_data, use_ti=False):
        self.use_ti = use_ti
        self.samples = []
        skipped = 0

        for _, row in df.iterrows():
            ticker = row['ticker']
            if ticker not in price_data:
                skipped += 1
                continue

            start = int(row['window_row_start'])
            end   = int(row['window_row_end'])
            label = LABEL_TO_IDX[row['label']]
            pct   = float(row['pct_change'])

            pdf = price_data[ticker]
            if end >= len(pdf):
                skipped += 1
                continue

            self.samples.append((ticker, start, end, label, pct))

        if skipped:
            print(f'      {skipped} samples skipped (missing ticker or out of range).')

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        ticker, start, end, label, pct = self.samples[idx]
        pdf = price_data[ticker]
        window = pdf.iloc[start:end+1]

        # ── Extract features ──────────────────────────────────────────
        ohlcv = window[OHLCV_COLS].values.astype(np.float32)

        # ── Min-max normalize OHLC together ───────────────────────────
        price_vals = ohlcv[:, :4]  # O, H, L, C
        p_min, p_max = price_vals.min(), price_vals.max()
        price_norm = (price_vals - p_min) / (p_max - p_min + 1e-8)

        # ── Min-max normalize Volume separately ───────────────────────
        vol = ohlcv[:, 4:5]
        v_min, v_max = vol.min(), vol.max()
        vol_norm = (vol - v_min) / (v_max - v_min + 1e-8)

        features = np.concatenate([price_norm, vol_norm], axis=1)  # (40, 5)

        # ── Optional: add technical indicators ────────────────────────
        if self.use_ti:
            ti_vals = window[TI_COLS].values.astype(np.float32)
            # Replace NaN with 0 (from TI warm-up periods)
            ti_vals = np.nan_to_num(ti_vals, nan=0.0)
            # Min-max normalize each TI independently
            for col_i in range(ti_vals.shape[1]):
                col = ti_vals[:, col_i]
                c_min, c_max = col.min(), col.max()
                ti_vals[:, col_i] = (col - c_min) / (c_max - c_min + 1e-8)
            features = np.concatenate([features, ti_vals], axis=1)  # (40, 10)

        tensor = torch.from_numpy(features)  # (40, input_size)
        return tensor, label

    @property
    def pct_changes(self):
        return [s[4] for s in self.samples]

    @property
    def targets(self):
        return [s[3] for s in self.samples]

print('OHLCVDataset class defined.')
print(f'  OHLCV columns: {OHLCV_COLS}')
print(f'  TI columns:    {TI_COLS}')

# ═══════════════════════════════════════════════════════════════════════════════
# CELL 6 — MODEL DEFINITION
# ═══════════════════════════════════════════════════════════════════════════════
# Simple LSTM → Linear classifier.
# Takes the LAST hidden state of the top layer as the sequence representation.
# Architecture follows Korean paper recommendations adapted for smaller data.
# ═══════════════════════════════════════════════════════════════════════════════

class AI4FinLSTM(nn.Module):
    """LSTM baseline for 3-class financial time series classification.

    Architecture:
        Input (batch, seq_len, input_size)
          → LSTM (hidden_size, num_layers, dropout)
          → last hidden state (batch, hidden_size)
          → Dropout(0.5)
          → Linear(hidden_size, 3)
    """
    def __init__(self, input_size, hidden_size=64, num_layers=2, dropout=0.3):
        super().__init__()
        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout if num_layers > 1 else 0.0,
        )
        self.classifier = nn.Sequential(
            nn.Dropout(p=0.5),
            nn.Linear(hidden_size, NUM_CLASSES),
        )
        # Initialize classifier weights
        for m in self.classifier.modules():
            if isinstance(m, nn.Linear):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)

    def forward(self, x):
        # x: (batch, seq_len, input_size)
        lstm_out, (h_n, c_n) = self.lstm(x)
        # h_n: (num_layers, batch, hidden_size) — take last layer
        last_hidden = h_n[-1]  # (batch, hidden_size)
        return self.classifier(last_hidden)


# ── Verify ────────────────────────────────────────────────────────────────────
for v in VARIANTS:
    _tmp = AI4FinLSTM(input_size=v['input_size'], hidden_size=HIDDEN_SIZE,
                      num_layers=NUM_LAYERS, dropout=DROPOUT)
    n_params = sum(p.numel() for p in _tmp.parameters())
    print(f"{v['name']}: input_size={v['input_size']}  params={n_params:,}")
    del _tmp

# ═══════════════════════════════════════════════════════════════════════════════
# CELL 7 — TRAIN / EVAL FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════════
# Identical logic to the Swin-T notebook, just without AMP (LSTM is tiny).
# ═══════════════════════════════════════════════════════════════════════════════

def train_epoch(model, loader, optimizer, criterion):
    model.train()
    running_loss = 0.0
    all_preds, all_labels = [], []
    for inputs, labels in tqdm(loader, desc='    train', leave=False):
        inputs = inputs.to(DEVICE)
        labels = labels.to(DEVICE)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        running_loss += loss.item() * inputs.size(0)
        all_preds.append(torch.argmax(outputs.detach(), dim=1).cpu())
        all_labels.append(labels.cpu())
    all_preds  = torch.cat(all_preds).numpy()
    all_labels = torch.cat(all_labels).numpy()
    _, _, macro_f1, _ = precision_recall_fscore_support(
        all_labels, all_preds, average='macro', zero_division=0)
    return running_loss / len(loader.dataset), accuracy_score(all_labels, all_preds), macro_f1


def eval_epoch(model, loader, criterion):
    model.eval()
    running_loss = 0.0
    all_preds, all_labels, all_probs = [], [], []
    with torch.no_grad():
        for inputs, labels in tqdm(loader, desc='    eval ', leave=False):
            inputs = inputs.to(DEVICE)
            labels = labels.to(DEVICE)
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            running_loss += loss.item() * inputs.size(0)
            probs = torch.softmax(outputs.float(), dim=1)
            all_preds.append(torch.argmax(probs, dim=1).cpu())
            all_labels.append(labels.cpu())
            all_probs.append(probs.cpu())
    all_preds  = torch.cat(all_preds).numpy()
    all_labels = torch.cat(all_labels).numpy()
    all_probs  = torch.cat(all_probs).numpy()
    _, _, macro_f1, _ = precision_recall_fscore_support(
        all_labels, all_preds, average='macro', zero_division=0)
    recall_pc = recall_score(all_labels, all_preds, labels=[0,1,2], average=None, zero_division=0)
    try:
        auc = roc_auc_score(all_labels, all_probs, multi_class='ovr', average='macro')
    except ValueError:
        auc = None
    return (running_loss / len(loader.dataset),
            accuracy_score(all_labels, all_preds),
            macro_f1, auc, all_preds, all_labels, all_probs, recall_pc)

print('Train/eval functions defined.')

# ═══════════════════════════════════════════════════════════════════════════════
# CELL 8 — FINANCIAL METRICS & PLOT HELPERS
# ═══════════════════════════════════════════════════════════════════════════════

def financial_metrics(test_preds, pct_changes, fwd_dates=None):
    """
    Portfolio-level financial metrics.
    - Sharpe: daily portfolio returns (mean across stocks per day), active days only.
    - MDD: relative drawdown on compounded daily portfolio equity curve.
    - Profit factor, win rate, total trades: individual active trades.
    """
    positions     = np.zeros(len(test_preds))
    positions[test_preds == LABEL_TO_IDX['Bullish']] =  1.0
    positions[test_preds == LABEL_TO_IDX['Bearish']] = -1.0
    trade_returns = positions * pct_changes

    # ── Portfolio daily returns ───────────────────────────────────────────────
    if fwd_dates is not None:
        dates    = pd.to_datetime(fwd_dates)
        daily_df = pd.DataFrame({'ret': trade_returns, 'date': dates})
        daily    = daily_df.groupby('date')['ret'].mean().sort_index().values
    else:
        daily = trade_returns

    # ── Sharpe on active days only ────────────────────────────────────────────
    active_daily = daily[daily != 0]
    if len(active_daily) >= 2 and active_daily.std() > 0:
        sharpe = float((active_daily.mean() / active_daily.std()) * np.sqrt(252 / FWD_DAYS))
    else:
        sharpe = 0.0

    # ── MDD on compound equity curve ──────────────────────────────────────────
    equity       = np.cumprod(1 + daily)
    peak         = np.maximum.accumulate(equity)
    max_drawdown = float(((equity - peak) / peak).min())

    # ── Trade-level metrics ───────────────────────────────────────────────────
    active        = trade_returns[trade_returns != 0]
    pos_ret       = trade_returns[trade_returns > 0].sum()
    neg_ret       = trade_returns[trade_returns < 0].sum()
    profit_factor = float(pos_ret / abs(neg_ret)) if neg_ret != 0 else float('inf')
    total_trades  = int(len(active))
    win_rate      = float((active > 0).sum() / total_trades) if total_trades > 0 else 0.0

    return sharpe, max_drawdown, profit_factor, win_rate, total_trades

def plot_training_curves(history_df, walk_id, best_epoch, save_dir, variant_name):
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
    for ax, tc, vc, title in [
        (ax1, 'train_loss', 'val_loss', 'Loss'),
        (ax2, 'train_f1',  'val_f1',   'Macro-F1'),
    ]:
        ax.plot(history_df['epoch'], history_df[tc], label='Train')
        ax.plot(history_df['epoch'], history_df[vc], label='Val')
        ax.axvline(best_epoch, color='k', linestyle='--', alpha=0.5, label='Best')
        ax.set_title(f'Walk {walk_id:02d} — {title} ({variant_name})')
        ax.set_xlabel('Epoch')
        ax.legend()
    fig.tight_layout()
    fig.savefig(os.path.join(save_dir, f'walk_{walk_id:02d}_training_curves.png'), dpi=100)
    plt.close()


def plot_confusion_matrix(labels, preds, walk_id, save_dir, variant_name):
    cm      = confusion_matrix(labels, preds)
    cm_norm = cm.astype(float) / (cm.sum(axis=1, keepdims=True) + 1e-8)
    annot   = np.array([[f'{v:.1%}\n({c})' for v, c in zip(rn, rc)]
                         for rn, rc in zip(cm_norm, cm)])
    fig, ax = plt.subplots(figsize=(7, 6))
    sns.heatmap(cm_norm, annot=annot, fmt='', cmap='Blues',
                xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES, ax=ax)
    ax.set_ylabel('True'); ax.set_xlabel('Predicted')
    ax.set_title(f'Walk {walk_id:02d} — Confusion Matrix ({variant_name})')
    fig.tight_layout()
    fig.savefig(os.path.join(save_dir, f'walk_{walk_id:02d}_confusion_matrix.png'), dpi=100)
    plt.close()

print('Financial metrics & plot helpers defined.')

# ═══════════════════════════════════════════════════════════════════════════════
# CELL 9 — INFERENCE FUNCTION
# ═══════════════════════════════════════════════════════════════════════════════
# After training, run full inference on test set and build trade log DataFrame
# with the same columns as the image-model inference notebook.
# ═══════════════════════════════════════════════════════════════════════════════

@torch.no_grad()
def run_full_inference(model, test_df_walk, price_data, use_ti):
    """Run inference on every test sample and return a trade log DataFrame."""
    model.eval()
    results = []

    for _, row in test_df_walk.iterrows():
        ticker = row['ticker']
        if ticker not in price_data:
            continue

        start = int(row['window_row_start'])
        end   = int(row['window_row_end'])
        pdf   = price_data[ticker]
        if end >= len(pdf):
            continue

        # Build input tensor (same logic as Dataset)
        window = pdf.iloc[start:end+1]
        ohlcv = window[OHLCV_COLS].values.astype(np.float32)

        price_vals = ohlcv[:, :4]
        p_min, p_max = price_vals.min(), price_vals.max()
        price_norm = (price_vals - p_min) / (p_max - p_min + 1e-8)
        vol = ohlcv[:, 4:5]
        v_min, v_max = vol.min(), vol.max()
        vol_norm = (vol - v_min) / (v_max - v_min + 1e-8)
        features = np.concatenate([price_norm, vol_norm], axis=1)

        if use_ti:
            ti_vals = window[TI_COLS].values.astype(np.float32)
            ti_vals = np.nan_to_num(ti_vals, nan=0.0)
            for col_i in range(ti_vals.shape[1]):
                col = ti_vals[:, col_i]
                c_min, c_max = col.min(), col.max()
                ti_vals[:, col_i] = (col - c_min) / (c_max - c_min + 1e-8)
            features = np.concatenate([features, ti_vals], axis=1)

        x = torch.from_numpy(features).unsqueeze(0).to(DEVICE)  # (1, 40, F)
        logits = model(x)
        probs = torch.softmax(logits.float(), dim=1).cpu().numpy()[0]
        pred_idx = probs.argmax()

        # Position: +1 bull, -1 bear, 0 neutral
        position = {0: -1, 1: 1, 2: 0}[pred_idx]
        trade_ret = position * float(row['pct_change'])

        results.append({
            'walk_id':      int(row.get('walk_id', 0)),
            'ticker':       ticker,
            'window_start': row['window_start'],
            'window_end':   row['window_end'],
            'fwd_start':    row['fwd_start'],
            'fwd_end':      row['fwd_end'],
            'entry_close':  float(row['entry_close']),
            'exit_close':   float(row['exit_close']),
            'pct_change':   float(row['pct_change']),
            'true_label':   row['label'],
            'pred_label':   IDX_TO_LABEL[pred_idx],
            'correct':      row['label'] == IDX_TO_LABEL[pred_idx],
            'confidence':   float(probs[pred_idx]),
            'prob_bearish': float(probs[0]),
            'prob_bullish': float(probs[1]),
            'prob_neutral': float(probs[2]),
            'position':     position,
            'trade_return': trade_ret,
        })

    return pd.DataFrame(results)

print('Inference function defined.')

# ═══════════════════════════════════════════════════════════════════════════════
# CELL 10 — MAIN WALK LOOP (TRAIN + INFERENCE)
# ═══════════════════════════════════════════════════════════════════════════════
# Loops through each variant, then each walk.
# Trains the LSTM, evaluates on test, runs full inference, saves everything.
# ═══════════════════════════════════════════════════════════════════════════════

walk_ids = sorted(meta_df['walk_id'].unique())
print(f'Total walks: {len(walk_ids)}')

all_variant_results = {}  # variant_name → list of walk result dicts
all_trade_logs = {}       # variant_name → concatenated trade log DataFrame

for variant in VARIANTS:
    v_name  = variant['name']
    use_ti  = variant['use_ti']
    in_size = variant['input_size']

    v_dir = os.path.join(RESULTS_DIR, v_name)
    os.makedirs(v_dir, exist_ok=True)

    print(f"\n{'═'*70}")
    print(f"  VARIANT: {v_name}  (input_size={in_size}, use_ti={use_ti})")
    print(f"{'═'*70}")

    walk_results = []
    walk_trade_logs = []

    for walk_id in walk_ids:
        print(f"\n{'─'*60}")
        print(f"  WALK {walk_id} / {len(walk_ids)}  [{v_name}]")
        print(f"{'─'*60}")

        model_path  = os.path.join(v_dir, f'walk_{walk_id:02d}_best_model.pth')
        log_path    = os.path.join(v_dir, f'walk_{walk_id:02d}_training_log.csv')
        result_path = os.path.join(v_dir, f'walk_{walk_id:02d}_result.csv')
        trade_path  = os.path.join(v_dir, f'walk_{walk_id:02d}_trade_log.csv')

        # ── Graceful resume ───────────────────────────────────────────
        if os.path.exists(model_path) and os.path.exists(result_path) and os.path.exists(trade_path):
            print(f'  Walk {walk_id} already done — loading saved results.')
            walk_results.append(pd.read_csv(result_path).iloc[0].to_dict())
            walk_trade_logs.append(pd.read_csv(trade_path))
            continue

        walk_df  = meta_df[meta_df['walk_id'] == walk_id]
        train_df = walk_df[walk_df['split'] == 'train']
        val_df   = walk_df[walk_df['split'] == 'val']
        test_df  = walk_df[walk_df['split'] == 'test']

        train_ds = OHLCVDataset(train_df, price_data, use_ti=use_ti)
        val_ds   = OHLCVDataset(val_df,   price_data, use_ti=use_ti)
        test_ds  = OHLCVDataset(test_df,  price_data, use_ti=use_ti)

        print(f'  Data — Train: {len(train_ds):,} | Val: {len(val_ds):,} | Test: {len(test_ds):,}')

        train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,
                                  num_workers=0, pin_memory=True)
        val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False,
                                  num_workers=0, pin_memory=True)
        test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False,
                                  num_workers=0, pin_memory=True)

        # ── Model ─────────────────────────────────────────────────────
        model = AI4FinLSTM(input_size=in_size, hidden_size=HIDDEN_SIZE,
                           num_layers=NUM_LAYERS, dropout=DROPOUT).to(DEVICE)

        # ── Class weighting (same as image models) ────────────────────
        class_counts  = np.bincount(train_ds.targets, minlength=NUM_CLASSES)
        class_weights = len(train_ds.targets) / (NUM_CLASSES * class_counts + 1e-6)
        criterion = nn.CrossEntropyLoss(weight=torch.FloatTensor(class_weights).to(DEVICE))

        optimizer = optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
        scheduler = optim.lr_scheduler.ReduceLROnPlateau(
            optimizer, mode='max', factor=0.3, patience=7, min_lr=1e-7)

        best_val_f1 = 0.0
        best_epoch  = 1
        patience_counter = 0
        best_state  = None
        history     = []

        for epoch in range(1, MAX_EPOCHS + 1):
            tr_loss, tr_acc, tr_f1 = train_epoch(model, train_loader, optimizer, criterion)
            vl_loss, vl_acc, vl_f1, vl_auc, _, _, _, recall_pc = eval_epoch(
                model, val_loader, criterion)

            scheduler.step(vl_f1)
            lr = optimizer.param_groups[0]['lr']

            print(f"  Ep {epoch:02d}/{MAX_EPOCHS} | "
                  f"TrLoss={tr_loss:.4f} TrF1={tr_f1:.4f} | "
                  f"VLoss={vl_loss:.4f} VF1={vl_f1:.4f} "
                  f"VAUC={f'{vl_auc:.4f}' if vl_auc is not None else 'N/A'} | "
                  f"Rec: Be={recall_pc[0]:.2f} Bu={recall_pc[1]:.2f} Ne={recall_pc[2]:.2f} | "
                  f"LR={lr:.2e}")

            history.append({
                'walk_id': walk_id, 'epoch': epoch,
                'train_loss': tr_loss, 'train_acc': tr_acc, 'train_f1': tr_f1,
                'val_loss': vl_loss, 'val_acc': vl_acc, 'val_f1': vl_f1,
                'val_auc': vl_auc, 'lr': lr,
            })

            if vl_f1 > best_val_f1:
                best_val_f1 = vl_f1
                best_epoch  = epoch
                best_state  = {k: v.cpu().clone() for k, v in model.state_dict().items()}
                patience_counter = 0
                print(f'    ★ New best F1={vl_f1:.4f}')
            else:
                patience_counter += 1

            if patience_counter >= PATIENCE_ES:
                print(f'  Early stopping at epoch {epoch}.')
                break

        # ── Save training log & plots ─────────────────────────────────
        history_df = pd.DataFrame(history)
        history_df.to_csv(log_path, index=False)
        plot_training_curves(history_df, walk_id, best_epoch, v_dir, v_name)

        # ── Load best model & evaluate on test ────────────────────────
        model.load_state_dict({k: v.to(DEVICE) for k, v in best_state.items()})
        torch.save(best_state, model_path)

        te_loss, te_acc, te_f1, te_auc, te_preds, te_labels, te_probs, _ = \
            eval_epoch(model, test_loader, criterion)

        plot_confusion_matrix(te_labels, te_preds, walk_id, v_dir, v_name)

        kappa = cohen_kappa_score(te_labels, te_preds)
        mcc   = matthews_corrcoef(te_labels, te_preds)
        print(f'\n  Classification Report — Walk {walk_id} ({v_name}):')
        print(classification_report(te_labels, te_preds, target_names=CLASS_NAMES, zero_division=0))

        sharpe, max_dd, pf, wr, n_trades = financial_metrics(
            te_preds, np.array(test_ds.pct_changes))

        walk_result = {
            'walk_id': walk_id, 'best_val_f1': best_val_f1,
            'test_accuracy': te_acc, 'test_macro_f1': te_f1, 'test_auc': te_auc,
            'cohen_kappa': kappa, 'mcc': mcc,
            'sharpe_ratio': sharpe, 'max_drawdown': max_dd,
            'profit_factor': pf, 'win_rate': wr, 'total_trades': n_trades,
        }
        walk_results.append(walk_result)
        pd.DataFrame([walk_result]).to_csv(result_path, index=False)

        # ── Full inference for trade log ──────────────────────────────
        print(f'  Running full inference for trade log...')
        trade_log = run_full_inference(model, test_df, price_data, use_ti)
        trade_log['walk_id'] = walk_id
        trade_log.to_csv(trade_path, index=False)
        walk_trade_logs.append(trade_log)

        print(f'  Walk {walk_id}: Acc={te_acc:.4f} F1={te_f1:.4f} '
              f'Sharpe={sharpe:.4f} Trades={n_trades}')

        # ── Cleanup ───────────────────────────────────────────────────
        del model, optimizer, scheduler, criterion
        del train_loader, val_loader, test_loader
        del train_ds, val_ds, test_ds
        torch.cuda.empty_cache()

    # ── Store results for this variant ────────────────────────────────
    all_variant_results[v_name] = walk_results
    all_trade_logs[v_name] = pd.concat(walk_trade_logs, ignore_index=True)

print(f'\n\nAll variants complete.')

# ═══════════════════════════════════════════════════════════════════════════════
# CELL 11 — AGGREGATE RESULTS & SAVE
# ═══════════════════════════════════════════════════════════════════════════════

for v_name, walk_results in all_variant_results.items():
    v_dir = os.path.join(RESULTS_DIR, v_name)
    results_df = pd.DataFrame(walk_results)
    results_df.to_csv(os.path.join(v_dir, 'per_walk_results.csv'), index=False)

    pf_clean = results_df['profit_factor'].replace([np.inf, -np.inf], np.nan)
    avg = {
        'Image Type':        'OHLCV',
        'Experiment':        v_name,
        'Num Walks':         len(walk_ids),
        'Avg Best Val F1':   results_df['best_val_f1'].mean(),
        'Avg Test Accuracy': results_df['test_accuracy'].mean(),
        'Avg Test Macro-F1': results_df['test_macro_f1'].mean(),
        'Std Test Macro-F1': results_df['test_macro_f1'].std(),
        'Avg Test AUC':      results_df['test_auc'].dropna().mean(),
        'Std Test AUC':      results_df['test_auc'].dropna().std(),
        'Avg Cohen Kappa':   results_df['cohen_kappa'].mean(),
        'Avg MCC':           results_df['mcc'].mean(),
        'Avg Sharpe Ratio':  results_df['sharpe_ratio'].mean(),
        'Std Sharpe Ratio':  results_df['sharpe_ratio'].std(),
        'Avg Max Drawdown':  results_df['max_drawdown'].mean(),
        'Avg Profit Factor': pf_clean.mean(),
        'Avg Win Rate':      results_df['win_rate'].mean(),
        'Avg Total Trades':  results_df['total_trades'].mean(),
    }
    summary_df = pd.DataFrame([avg])
    summary_df.to_csv(os.path.join(v_dir, 'aggregated_summary.csv'), index=False)

    print(f'\n{"═"*60}')
    print(f'  AGGREGATED RESULTS — {v_name}')
    print(f'{"═"*60}')
    display(summary_df.T.rename(columns={0: 'Value'}))

    # Append to master summary
    master_path = os.path.join(DRIVE_DIR, 'results', 'all_experiments_summary.csv')
    if os.path.exists(master_path):
        master_df = pd.concat([pd.read_csv(master_path), summary_df], ignore_index=True)
    else:
        master_df = summary_df
    master_df.to_csv(master_path, index=False)
    print(f'Appended to: {master_path}')

# ═══════════════════════════════════════════════════════════════════════════════
# CELL 12 — SAVE TRADE LOGS TO EXCEL (for inference notebook compatibility)
# ═══════════════════════════════════════════════════════════════════════════════
# Saves trade logs in the same Excel format as the image-model inference notebook.
# This means the confidence/regime analysis notebook works on it with zero changes.
# ═══════════════════════════════════════════════════════════════════════════════

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

HEADER_FONT = Font(name='Arial', bold=True, color='FFFFFF', size=11)
HEADER_FILL = PatternFill('solid', fgColor='2F5496')
DATA_FONT   = Font(name='Arial', size=10)
GREEN_FILL  = PatternFill('solid', fgColor='C6EFCE')
RED_FILL    = PatternFill('solid', fgColor='FFC7CE')

OUTPUT_XLSX = os.path.join(RESULTS_DIR, 'detailed_model_results_lstm.xlsx')

wb = openpyxl.Workbook()
wb.remove(wb.active)

for v_name, trade_log in all_trade_logs.items():
    # ── Trades sheet ──────────────────────────────────────────────
    trade_cols = [
        'walk_id', 'ticker', 'window_start', 'window_end',
        'fwd_start', 'fwd_end', 'entry_close', 'exit_close',
        'pct_change', 'true_label', 'pred_label', 'correct',
        'confidence', 'prob_bearish', 'prob_bullish', 'prob_neutral',
        'position', 'trade_return',
    ]
    tl = trade_log[trade_cols].copy()
    ws = wb.create_sheet(f'{v_name}_Trades')

    # Write headers
    for c, col_name in enumerate(tl.columns, 1):
        cell = ws.cell(row=1, column=c, value=col_name)
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        cell.alignment = Alignment(horizontal='center', wrap_text=True)

    # Write data
    for r, row_data in enumerate(tl.itertuples(index=False), 2):
        for c, val in enumerate(row_data, 1):
            cell = ws.cell(row=r, column=c)
            if isinstance(val, (np.integer,)): val = int(val)
            elif isinstance(val, (np.floating,)): val = float(val)
            elif isinstance(val, (np.bool_,)): val = bool(val)
            cell.value = val
            cell.font = DATA_FONT

    # Color correct/wrong and trade_return columns
    for r in range(2, len(tl) + 2):
        cell_c = ws.cell(row=r, column=12)  # correct
        cell_c.fill = GREEN_FILL if cell_c.value else RED_FILL
        cell_r = ws.cell(row=r, column=18)  # trade_return
        if isinstance(cell_r.value, (int, float)):
            cell_r.fill = GREEN_FILL if cell_r.value > 0 else (RED_FILL if cell_r.value < 0 else PatternFill())

    # Auto-width
    for c in range(1, len(trade_cols) + 1):
        ws.column_dimensions[get_column_letter(c)].width = max(len(str(trade_cols[c-1])) + 4, 13)
    ws.freeze_panes = 'A2'
    ws.auto_filter.ref = ws.dimensions

    print(f'  {v_name}_Trades: {len(tl):,} rows')

wb.save(OUTPUT_XLSX)
print(f'\n✓ Excel saved to: {OUTPUT_XLSX}')
print(f'  Sheets: {wb.sheetnames}')
print(f'\n  This file is compatible with the confidence/regime analysis notebook.')

# ═══════════════════════════════════════════════════════════════════════════════
# CELL 13 — FINAL COMPARISON TABLE
# ═══════════════════════════════════════════════════════════════════════════════

print('\n' + '═'*70)
print('  LSTM BASELINE — FINAL COMPARISON')
print('═'*70)

rows = []
for v_name, walk_results in all_variant_results.items():
    rdf = pd.DataFrame(walk_results)
    pf_clean = rdf['profit_factor'].replace([np.inf, -np.inf], np.nan)
    rows.append({
        'Model': v_name,
        'Avg F1': f"{rdf['test_macro_f1'].mean():.4f} ± {rdf['test_macro_f1'].std():.4f}",
        'Avg Acc': f"{rdf['test_accuracy'].mean():.4f}",
        'Avg AUC': f"{rdf['test_auc'].dropna().mean():.4f}",
        'Avg MCC': f"{rdf['mcc'].mean():.4f}",
        'Avg Sharpe': f"{rdf['sharpe_ratio'].mean():.4f}",
        'Avg MDD': f"{rdf['max_drawdown'].mean():.4f}",
        'Avg PF': f"{pf_clean.mean():.4f}",
    })

comparison = pd.DataFrame(rows)
display(comparison)

print(f'\n✓ All results saved to: {RESULTS_DIR}')
print(f'✓ Trade log Excel: {OUTPUT_XLSX}')
print(f'\nNext step: run confidence/regime analysis notebook on the LSTM results.')